# Generated by Django 5.2.5 on 2025-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
