# Generated by Django 5.2.5 on 2025-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_current_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_year_of_study',
            field=models.IntegerField(),
        ),
    ]
