# Generated by Django 5.2.5 on 2025-08-26 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_current_year_of_study'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='belongs_to_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club'),
        ),
    ]
