# Generated by Django 5.2.5 on 2025-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_belongs_to_club'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='belongs_to_club',
        ),
        migrations.AddField(
            model_name='customuser',
            name='belongs_to_club',
            field=models.ManyToManyField(blank=True, to='clubs.club'),
        ),
    ]
