# Generated by Django 5.2.5 on 2025-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_belongs_to_club_and_more'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='belongs_to_club',
            field=models.ManyToManyField(blank=True, related_name='members', to='clubs.club'),
        ),
    ]
