# Generated by Django 5.2.5 on 2025-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_belongs_to_club_and_more'),
        ('tasks', '0002_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='accounts.customuser'),
        ),
    ]
