# Generated by Django 5.2.5 on 2025-08-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_abreaviation',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
