# Generated by Django 5.2.5 on 2025-08-27 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_belongs_to_club'),
        ('clubs', '0002_club_club_abreaviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_clubs', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
